version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: task-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass-admin
    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  task-v2-api:
    build: .
    container_name: task-app
    depends_on:
      - postgres
    ports:
      - "8081:8081"

